{{- range $name, $svc := .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-{{ $name }}
spec:
  replicas: {{ $svc.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ $.Release.Name }}-{{ $name }}
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}-{{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: {{ $svc.image }}
          ports:
            {{- range $svc.ports }}
            - containerPort: {{ .containerPort }}
            {{- end }}
          env:
            {{- if $svc.env }}
            {{- range $key, $val := $svc.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
            {{- end }}
          {{- if $svc.secrets }}
          envFrom:
            - secretRef:
                name: {{ $.Release.Name }}-{{ $name }}-secret
          {{- end }}
          volumeMounts:
            {{- range $svc.volumeMounts }}
            - name: {{ $.Release.Name }}-{{ $name }}-pvc
              mountPath: {{ .mountPath }}
              subPath: {{ .subPath | default "" }}
            {{- end }}
            {{- range $svc.secretMounts }}
            - name: {{ $.Release.Name }}-{{ $name }}-secret-{{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: true
            {{- end }}
      volumes:
        {{- if $svc.storage }}
        - name: {{ $.Release.Name }}-{{ $name }}-pvc
          persistentVolumeClaim:
            claimName: {{ $.Release.Name }}-{{ $name }}-pvc
        {{- end }}
        {{- range $svc.secretMounts }}
        - name: {{ $.Release.Name }}-{{ $name }}-secret-{{ .name }}
          secret:
            secretName: {{ $.Release.Name }}-{{ $name }}-secret
            {{- if .items }}
            items:
              {{- range .items }}
              - key: {{ .key }}
                path: {{ .path }}
              {{- end }}
            {{- end }}
        {{- end }}
---
{{- end }}
