{{- if eq .Values.secretProvider "external" }}
{{- range $name, $svc := .Values.services }}
{{- if $svc.secrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $.Release.Name }}-{{ $name }}-externalsecret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: {{ ternary $.Values.existingSecretStoreRef.kind "SecretStore" $.Values.useExistingSecretStore }}
    name: {{ ternary $.Values.existingSecretStoreRef.name ($.Values.externalSecretStore | default "default-secret-store") $.Values.useExistingSecretStore }}
  target:
    name: {{ $.Release.Name }}-{{ $name }}-secret
  data:
    {{- range $key, $_ := $svc.secrets }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ printf "%s/%s/%s" $.Release.Name $name $key | lower }}
    {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
