apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-web"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.web.port }}
      targetPort: {{ .Values.web.port }}
      nodePort: {{ .Values.web.servicePort | default 0 }}
  selector:
    app: "{{ .Release.Name }}-web"
